line.collideswith() + tests
novialriptide/pygame_geometry pull request #98
Opened 2022-09-24 10:44 UTC by ScriptLineStudios

#64

2022-09-24 11:46 UTC, itzpr3d4t0r approved these changes
LGTM!

2022-09-25 07:47 UTC, novialriptide requested changes

2022-09-25 07:47 UTC, novialriptide commented on geometry.pyi
> +    def collideswith(self, other: _CanBeCollided) -> bool: ...
This is between two `colliderect()` functions, could you move them somewhere else?

2022-09-25 20:59 UTC, Emc2356 approved these changes
LGTM!

2022-09-26 01:44 UTC, merged